# This is a placeholder workflow file. Add your GitHub Actions workflows here.
name: Blank Workflow
on:
  push:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Say Hello
        run: echo "Hello, world!" 